# Generated by Django 4.2.6 on 2023-10-19 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Colillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Hora', models.DateField()),
                ('cant_colillas', models.IntegerField()),
                ('colillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colillero_project.colillero')),
            ],
        ),
    ]
