# Generated by Django 4.2.6 on 2023-11-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colillero_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colillero',
            name='estado',
            field=models.CharField(choices=[('vacio', 'Vacío'), ('proximo_llenado', 'Próximo a Llenarse'), ('lleno', 'Lleno')], default='vacio', max_length=20),
        ),
    ]
